### ISSUE TITLE
How to use UDOC.js in an electron application for converting emf files to pdf?

### ISSUE THREAD

**Issue by AbdulRazak02** [photopea/UDOC.js#3]
Can you please provide some examples for converting an EMF file to Pdf in a Electron application?

**Comment by photopea** [comment]
Hi, I am not familiar with Electron :( 

In Javascript, you can do it like this (buff is ArrayBuffer of a PDF):

    var w = new ToPDF();  FromEMF.Parse(buff, w);  // now, w.buffer is the ArrayBuffer of your file
