### ISSUE TITLE
Hi, I have a problem using FromWMF. Js and tocontext2d.js

### ISSUE THREAD

**Issue by jscz3w** [photopea/UDOC.js#4]
Hi, I have a problem using FromWMF. Js and tocontext2d.js ,property  undefined. I don't know how to fix it! thank you！

   Uncaught TypeError: Cannot read property 't' of undefined
    at Function.FromWMF.Parse (FromWMF.js:71)
……………………
				var ind = rU(buff, loff);  loff+=2;
				var co = tab[ind];  //console.log(co);
				if(co.t=="br") {
					prms.fill=co.stl!=1;
					if     (co.stl==0) {}
					else if(co.stl==1) {}
					else throw co.stl+" e";
					gst.colr=co.clr;
					if(co.htc!=0) throw "e";
				}
……………………

my code 

   var xhr = new XMLHttpRequest();
    xhr.open('GET', ‘./img/208.WMF’,true);
    xhr.responseType = 'arraybuffer';
    
    xhr.onload = function (e) {
      var buffer = xhr.response;
      var pageI = 0, scale = 1;
        
      var genv = new ToContext2D(pageI,scale);
      console.log(buffer);
      FromWMF.Parse(buffer,genv); 
     document.body.appendChild(genv.canvas);
     }; 
  xhr.send();

**Comment by photopea** [comment]
Hi, there may be a bug in the FromWMF parser . Can you try to open your WMF file in www.Photopea.com ? If it does not open, please, send your WMF file to support@photopea.com , so we can fix it.

**Comment by photopea** [comment]
Thank you for sending a file!  Hi, the old FromWMF parser did not support the text at all. I fixed it, please, use the new FromWMF.js

I was not able to implement the support of Chinese text :( it seems like there is some strange text charset and encoding (not Unicode).
