### ISSUE TITLE
EMF doesn't load

### ISSUE THREAD

**Issue by pablopla** [photopea/UDOC.js#5]
The attached EMF file doesn't open in photopea.

[photopea.zip](https://github.com/photopea/UDOC.js/files/2613223/photopea.zip)

**Comment by photopea** [comment]
Hi, I just updated Photopea and FromEMF.js . Your EMF file should work fine now.

However, the text in your EMF, according to the EMF specification, should be Unicode UTF16 with codes 156,155,154, however, MS Paint displays some Hebrew letters which are not UTF16 156,155,154, I don't know how they process it :(

**Comment by pablopla** [comment]
Thank you for the update.
I've created the EMF with PowerPoint. I've typed few Hebrew letters and Saved As Enhanced Meta file.
Why is this issue closed if the EMF isn't displayed properly?
