### ISSUE TITLE
FromPS don't work

### ISSUE THREAD

**Issue by tomieric** [photopea/UDOC.js#6]
I have an example:

**HTML**
```html
<input type="file" id="file" />
```

**JavaScript**

```
import FromPS from './FromPS'
import ToContext2D from './ToContext2D'

const $file = document.getElementById('file')

const canvasInstance = new ToContext2D(0, 1)

document.body.appendChild(canvasInstance.canvas)

canvasInstance.canvas.width = 500
canvasInstance.canvas.height = 500

$file.addEventListener('change', e => {
  console.log(e.target.files)
  const reader = new FileReader()
  reader.readAsArrayBuffer(e.target.files[0])
  reader.onload = () => {
    FromPS.Parse(reader.result, canvasInstance)
  }
})
```
The browser is crush!!!

> Google Chrome 75.0.3770.100（64 Bit）

How to use it about `fromPS.js`?

**Comment by tomieric** [comment]
It's well to open my PS file in Photopea.com, I want to compare the difference with `psd.js`.
The `psd.js` Cannot be resolved to parse layer effect(styles),like `shadow`,`strokes`.etc

**Comment by photopea** [comment]
So is your file PostScript or PSD?  FromPS.js is for PostScript files, not PSD files.  We do not provide any library for PSD files.
