### ISSUE TITLE
EMF data not recognized

### ISSUE THREAD

**Issue by guiohm** [photopea/UDOC.js#7]
Hi, first thank you for this lib.

I cannot figure out how to properly pass an emf file content to the parser. 

- I tried alongside other data in json with conetnt encoded in base64 then decoded with `atob()`
- I tried loading the file using the Fetch API, then getting the content with `result.text()`

Every time it keep looping inside the main `while(true)` loop and cannot find anything in `fnm`

Could you please give me a hint on the data type I should use?

**Comment by photopea** [comment]
Hi, can you open your EMF file in Photopea.com ? If not, can you send it to me?

**Comment by guiohm** [comment]
Well, sorry I should have found this one earlier... `Uint8Array` is loaded with an `ArrayBuffer`, so I just changed `result.text()` to `result.arrayBuffer()`.

**Comment by photopea** [comment]
Hi, I fixed a few things, but your EMF is still rendered incorrectly, see www.Photopea.com .

Would you like to become a maintainer of our EMF reader? You could fix bugs like these.

**Comment by guiohm** [comment]
Thanks for improving things. I'm not sure yet if I will take time (don't know how much needed either) to implement all the missing parts for the EMF files we use here.
Can you point me to any relevant tool to inspect EMFs or a documentation where I can find the missing parts?
Thanks

**Comment by photopea** [comment]
You can find the specification of the EMF format on the Microsofts website. Maybe you can find the EMF to PDF converter. PDF is supported by more programs than EMF.

**Comment by guiohm** [comment]
Indeed, thanks again for your help. As I just found there is an analyzer here : http://www.flounder.com/metafileexplorer.htm
And the Microsoft reference here : https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-emf/91c257d7-c39d-4a36-9b1f-63e3f73d30ca

**Comment by avonwyss** [comment]
@photopea The source code has not been updated since 2018, so the repo has not been updated with the EMF fixes you've made I guess? Could you update the code?

**Comment by photopea** [comment]
Hi, I changed my mind, I would like to keep this library private (not open-source), so I will delete the repository now.
